name: ci
permissions:
  contents: read
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test-provisioners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup-kind-cluster
        run: |
          .scripts/setup-kind-cluster.sh
      - name: test-provisioners
        run: |
          .scripts/test-provisioners.sh